#!/bin/bash
# ===============================================
# 🧩 Dynamic Subdomain Sync — Public Release v1.0.0
# ===============================================
# Author: Revi9x
# License: MIT
# -----------------------------------------------
# Description:
#   Automatically syncs DNS A-records from cPanel
#   with active Docker containers for game servers,
#   prioritizing UDP ports and common game port ranges.
#
# Features:
#   • Fetch DNS A-records from cPanel JSON API
#   • Detect Docker containers and map ports
#   • Prefers UDP for game traffic (Rust, CS2, etc.)
#   • Safe rollback and validation via Caddy
#   • Interactive first-time setup (auto-saves config)
#   • No external config files needed after first run
#
# Dependencies:
#   curl, jq, docker, bash ≥ 5
#
# Logs:
#   /var/log/syncsd.log
#
# Config Cache:
#   /etc/revive/config.env
#
# ===============================================

set -e

CONFIG_FILE="/etc/revive/config.env"
LOGFILE="/var/log/syncsd.log"
CADDYFILE="/etc/caddy/Caddyfile"
TMPFILE="/tmp/Caddyfile.sync"
EMAIL_DEFAULT="admin@yourdomain.com"
COMMON_PORTS=(25565 27015 27016 28015 7777 21212 8080 80)

mkdir -p "$(dirname "$LOGFILE")" /etc/revive
touch "$LOGFILE"
[[ -f "$CADDYFILE" ]] || echo "# Initial Caddyfile" > "$CADDYFILE"
[[ -f "${CADDYFILE}.bak" ]] || cp "$CADDYFILE" "${CADDYFILE}.bak"

# === Logging ===
log() { echo "$*" | tee -a "$LOGFILE"; }

# === Load or Create Config ===
if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "⚙️  Initial setup: please provide your environment info."
  read -rp "👉 cPanel Username: " CPANEL_USER
  read -rp "👉 cPanel API Token: " CPANEL_TOKEN
  read -rp "👉 cPanel Hostname (e.g., us01.hosting.com): " CPANEL_HOST
  read -rp "👉 Root Domain (e.g., example.com): " DOMAIN
  read -rp "👉 Admin Email for TLS (default: ${EMAIL_DEFAULT}): " EMAIL
  EMAIL=${EMAIL:-$EMAIL_DEFAULT}

  cat <<EOF > "$CONFIG_FILE"
CPANEL_USER="${CPANEL_USER}"
CPANEL_TOKEN="${CPANEL_TOKEN}"
CPANEL_HOST="${CPANEL_HOST}"
DOMAIN="${DOMAIN}"
EMAIL="${EMAIL}"
EOF
  chmod 600 "$CONFIG_FILE"
  echo "✅ Config saved to $CONFIG_FILE"
fi

# === Load Config ===
# shellcheck disable=SC1091
source "$CONFIG_FILE"

log ""
log "===== [ Dynamic Subdomain Sync — v1.0.0 ] ====="
log "🔍 Fetching DNS A records for ${DOMAIN}..."

# === Fetch DNS Records ===
JSON=$(curl -s -H "Authorization: cpanel ${CPANEL_USER}:${CPANEL_TOKEN}" \
  "https://${CPANEL_HOST}:2083/json-api/cpanel?cpanel_jsonapi_user=${CPANEL_USER}&cpanel_jsonapi_apiversion=2&cpanel_jsonapi_module=ZoneEdit&cpanel_jsonapi_func=fetchzone&domain=${DOMAIN}")

mapfile -t SUBDOMAINS < <(echo "$JSON" | jq -r '.cpanelresult.data[0].record[]? | select(.type=="A") | .name' \
  | sed 's/\.$//' | grep -E "\.${DOMAIN}$" | sed "s/\.${DOMAIN}$//" | sort -u)

if [[ ${#SUBDOMAINS[@]} -eq 0 ]]; then
  log "❌ No A-records found — aborting."
  exit 1
fi
log "✅ Retrieved ${#SUBDOMAINS[@]} A-records."

# === Filter malformed ===
VALID_SUBS=()
for sub in "${SUBDOMAINS[@]}"; do
  [[ -z "$sub" || "$sub" == "*" || ! "$sub" =~ ^[a-zA-Z0-9-]+$ ]] && {
    log "⚠️ Skipping malformed: '$sub'"
    continue
  }
  VALID_SUBS+=("$sub")
done

[[ ${#VALID_SUBS[@]} -eq 0 ]] && { log "❌ No valid subdomains remain."; exit 1; }

# === Docker Port Discovery ===
log "🔎 Scanning Docker containers..."
declare -A DOCKER_TCP_PORTS
declare -A DOCKER_UDP_PORTS

while read -r CID NAME; do
  TCP_PORTS=$(docker port "$CID" | grep '/tcp' | awk '{print $3}' | awk -F: '{print $NF}' | sort -u | xargs)
  UDP_PORTS=$(docker port "$CID" | grep '/udp' | awk '{print $3}' | awk -F: '{print $NF}' | sort -u | xargs)
  DOCKER_TCP_PORTS["$NAME"]="$TCP_PORTS"
  DOCKER_UDP_PORTS["$NAME"]="$UDP_PORTS"
done < <(docker ps --format '{{.ID}} {{.Names}}')

log "✅ Found ${#DOCKER_TCP_PORTS[@]} container(s)."
for name in "${!DOCKER_TCP_PORTS[@]}"; do
  [[ -z "${DOCKER_TCP_PORTS[$name]}" && -z "${DOCKER_UDP_PORTS[$name]}" ]] && continue
  log "   • $name → TCP[${DOCKER_TCP_PORTS[$name]}] UDP[${DOCKER_UDP_PORTS[$name]}]"
done

# === Pick most likely port ===
pick_port() {
  local udp="$1"; local tcp="$2"; local port=""
  if [[ -n "$udp" ]]; then
    for cp in "${COMMON_PORTS[@]}"; do
      [[ "$udp" =~ $cp ]] && { port="$cp"; break; }
    done
    [[ -z "$port" ]] && port=$(echo "$udp" | awk '{print $1}')
  elif [[ -n "$tcp" ]]; then
    for cp in "${COMMON_PORTS[@]}"; do
      [[ "$tcp" =~ $cp ]] && { port="$cp"; break; }
    done
    [[ -z "$port" ]] && port=$(echo "$tcp" | awk '{print $1}')
  fi
  echo "$port"
}

# === Build new config ===
log "🧱 Building new Caddyfile: $TMPFILE"
echo "# Auto-generated by RG Dynamic Subdomain Sync" > "$TMPFILE"
echo "" >> "$TMPFILE"

for sub in "${VALID_SUBS[@]}"; do
  FULL="${sub}.${DOMAIN}"
  BACKEND="panel:80"
  for cname in "${!DOCKER_TCP_PORTS[@]}"; do
    if [[ "$FULL" =~ $cname ]] || [[ "$sub" == "$cname" ]]; then
      UDP="${DOCKER_UDP_PORTS[$cname]}"
      TCP="${DOCKER_TCP_PORTS[$cname]}"
      PORT=$(pick_port "$UDP" "$TCP")
      [[ -n "$PORT" ]] && BACKEND="${cname}:${PORT}"
      break
    fi
  done
  cat <<EOF >> "$TMPFILE"
${FULL} {
    reverse_proxy ${BACKEND}
    tls ${EMAIL}
}

EOF
  log "• ${FULL} → ${BACKEND}"
done

[[ ! -s "$TMPFILE" ]] && { log "❌ Empty config — aborting."; exit 1; }
log "✅ Caddyfile structure verified."

# === Remove stale ===
log "🧹 Cleaning obsolete entries..."
EXISTING=$(grep -E '^[a-zA-Z0-9.-]+\s*\{' "$CADDYFILE" | awk '{print $1}' | sed 's/{//' | sort -u)
for entry in $EXISTING; do
  SUB=$(echo "$entry" | sed "s/\.${DOMAIN}//")
  [[ ! " ${VALID_SUBS[*]} " =~ " ${SUB} " ]] && {
    log "🗑️ Removing ${entry}"
    awk -v site="$entry" '
      BEGIN {keep=1}
      $0 ~ site" " {keep=0}
      /^\}/ && keep==0 {keep=1; next}
      keep {print}
    ' "$CADDYFILE" > "${CADDYFILE}.tmp" && mv "${CADDYFILE}.tmp" "$CADDYFILE"
  }
done

# === Validate & Reload ===
log "🔍 Validating configuration..."
if docker exec -i revive-caddy caddy validate --adapter caddyfile --config - < "$TMPFILE" >/dev/null 2>&1; then
  log "✅ Configuration valid."
  cp "$CADDYFILE" "${CADDYFILE}.bak"
  mv "$TMPFILE" "$CADDYFILE"
  docker exec revive-caddy caddy reload --config "$CADDYFILE" >/dev/null 2>&1 && log "🚀 Reload successful."
else
  log "❌ Validation failed — rollback initiated."
  cp "${CADDYFILE}.bak" "$CADDYFILE"
  docker exec revive-caddy caddy reload --config "$CADDYFILE" >/dev/null 2>&1
  cp "$TMPFILE" /tmp/Caddyfile.failed
fi

log "✅ Sync Complete — DNS and containers aligned."
log "========= 🛠️ Maintained by Revi9x 🛠️ ========="
